version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    ports:
      - '80:80'
    depends_on:
      - php
    env_file: '.env'
  php:
    build:
     context: .
     dockerfile: dockerfiles/php.dockerfile
    env_file: '.env'