services:
  server:
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    ports:
      - '80:80'
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - mysql
  php:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated
  mysql:
    image: mysql:8.4
    command: --max_allowed_packet=32505856 # Set higher max_allowed_packets to 32M to avoid sql connection error during migrate after install
    ports:
      - "3306:3306"
    env_file:
      - ./env/mysql.env
    volumes:
      - db-data:/var/lib/mysql 
  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html
  artisan:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/www/html
    entrypoint: ['php', '/var/www/html/artisan']


  vue:
    build:
        context: .
        dockerfile: dockerfiles/vue.dockerfile
    # image: node:14
    # working_dir: /vapp
    entrypoint:
      ['npm']
    volumes:
      - ./src/resources/vapp:/opt/vapp
    ports:
      - "5173:5173"
    command: "run dev"

volumes:
    db-data: